--
-- PostgreSQL database dump
--

-- Dumped from database version 13.16 (Debian 13.16-1.pgdg120+1)
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    name character varying(255),
    date character varying(255),
    string_id character varying(255)
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sku; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sku (
    sku_id bigint NOT NULL,
    product_id bigint,
    price integer,
    article integer,
    status character varying(255),
    CONSTRAINT sku_price_check CHECK ((price > 0)),
    CONSTRAINT sku_status_check CHECK (((status)::text = ANY (ARRAY[('есть на складе'::character varying)::text, ('нет на складе'::character varying)::text])))
);


ALTER TABLE public.sku OWNER TO postgres;

--
-- Name: sku_sku_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sku ALTER COLUMN sku_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sku_sku_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, name, date, string_id) FROM stdin;
1	Кроссовки	2024-10-19	\N
6	Кеды	2024-10-18	\N
7	Куртка	2018-06-10	\N
8	Футболка	2019-01-05	\N
9	Джинсы	2019-09-18	\N
10	Кроссовки	2020-02-22	\N
11	Шапка	2020-11-30	\N
12	Рубашка	2021-04-12	\N
13	Шорты	2021-08-09	\N
14	Пальто	2022-03-01	\N
15	Костюм	2022-10-20	\N
16	Туфли	2023-05-03	\N
17	Свитер	2023-12-14	\N
18	Пиджак	2018-04-25	\N
19	Рюкзак	2019-07-28	\N
20	Пояс	2020-12-15	\N
21	Носки	2021-02-10	\N
22	Очки	2021-09-21	\N
23	Перчатки	2022-06-05	\N
24	Шарф	2023-07-22	\N
\.


--
-- Data for Name: sku; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sku (sku_id, product_id, price, article, status) FROM stdin;
103	7	725	23456	нет на складе
104	8	845	34567	есть на складе
105	9	580	45678	есть на складе
106	10	390	56789	нет на складе
107	6	670	67890	есть на складе
108	11	450	78901	нет на складе
109	12	320	89012	нет на складе
110	13	600	90123	есть на складе
111	14	780	12346	есть на складе
112	15	510	23457	нет на складе
113	16	720	34568	есть на складе
114	1	865	45679	есть на складе
115	17	390	56780	нет на складе
116	18	670	67891	есть на складе
117	19	510	78902	нет на складе
118	20	430	89013	есть на складе
119	21	800	90124	есть на складе
120	22	250	12347	нет на складе
121	23	610	23458	нет на складе
122	24	750	34569	есть на складе
123	6	940	45680	нет на складе
124	7	455	56781	есть на складе
125	8	580	67892	нет на складе
126	9	380	78903	есть на складе
127	10	660	89014	нет на складе
128	11	370	90125	есть на складе
129	12	420	12348	нет на складе
130	1	830	23459	есть на складе
131	13	900	34570	нет на складе
132	14	260	45681	есть на складе
133	15	470	56782	нет на складе
134	16	780	67893	есть на складе
135	17	150	78904	нет на складе
136	18	900	89015	есть на складе
137	19	250	90126	нет на складе
138	20	890	12349	есть на складе
139	21	620	23460	нет на складе
140	22	420	34571	есть на складе
141	23	350	45682	нет на складе
142	24	900	56783	есть на складе
143	6	550	67894	нет на складе
144	7	310	78905	есть на складе
145	8	740	89016	нет на складе
146	1	830	90127	есть на складе
147	9	670	12350	нет на складе
148	10	560	23461	есть на складе
149	11	470	34572	нет на складе
150	12	390	45683	есть на складе
151	6	455	12345	есть на складе
\.


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 24, true);


--
-- Name: sku_sku_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sku_sku_id_seq', 199, true);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: sku sku_article_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sku
    ADD CONSTRAINT sku_article_key UNIQUE (article);


--
-- Name: sku sku_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sku
    ADD CONSTRAINT sku_pkey PRIMARY KEY (sku_id);


--
-- Name: sku sku_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sku
    ADD CONSTRAINT sku_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

